name: campusgo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.1.0

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  google_fonts: ^8.0.2
  flutter_riverpod: ^3.2.1
  loading_animation_widget: ^1.3.0

  path: ^1.9.1
  cached_network_image: ^3.4.1
  file_picker: ^10.3.10
  image_picker: ^1.1.2
  http: ^1.2.0
  collection: ^1.19.1
  intl: ^0.20.2
  audioplayers: ^6.6.0
  url_launcher: ^6.1.10
  flutter_local_notifications: ^21.0.0
  firebase_messaging: ^16.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/campusgo_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/campusgo_logo.png